export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADMIN_LOADED = 'ADMIN_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const INSTRUCTOR_LOADED = 'INSTRUCTOR_LOADED';
export const INSTRUCTOR_AUTH_ERROR = 'INSTRUCTOR_AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const INSTRUCTOR_LOGIN_SUCCESS = 'INSTRUCTOR_LOGIN_SUCCESS';
export const INSTRUCTOR_LOGIN_FAIL = 'INSRUCTOR_LOGIN_FAIL';
export const INSTRUCTOR_LOGOUT = 'INSTRUCTOR_LOGOUT';

export const GET_MODULE = 'GET_MODULE';
export const GET_MODULES = 'GET_MODULES';
export const MODULE_ERROR = 'MODULE_ERROR';
export const LOADING_TRUE = 'LOADING_TRUE';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';

export const GET_ADMIN = 'GET_ADMIN';
export const GET_ADMINS = 'GET_ADMINS';
export const ADMIN_ERROR = 'ADMIN_ERROR';

export const GET_INSTRUCTOR = 'GET_INSTRUCTOR';
export const GET_INSTRUCTORS = 'GET_INSTRUCTORS';
export const INSTRUCTOR_ERROR = 'INSTRUCTOR_ERROR';

export const GET_EMAILS = 'GET_EMAILS';
export const EMAILS_ERROR = 'EMAILS_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_SLOTS = 'GET_SLOTS';
export const SLOT_ERROR = 'SLOT_ERROR';

export const GET_VENUE = 'GET_VENUE';
export const GET_VENUES = 'GET_VENUES';
export const VENUE_ERROR = 'VENUE_ERROR';

export const GET_NOTICE = 'GET_NOTICE';
export const GET_NOTICES = 'GET_NOTICES';
export const NOTICE_ERROR = 'NOTICE_ERROR';

export const GET_LEAVE = 'GET_LEAVE';
export const GET_LEAVES = 'GET_LEAVES';
export const LEAVE_ERROR = 'LEAVE_ERROR';

export const GET_TIMETABLE = 'GET_TIMETABLE';
export const GET_TIMETABLES = 'GET_TIMETABLES';
export const TIMETABLE_ERROR = 'TIMETABLE_ERROR';
